project:
  type: website
  output-dir: docs

website:
  title: "Collaborative website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - href: Cody.qmd
        text: Cody Dettlaff

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    page-layout: full



